export const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Prix',
  description: 'AI-powered GitHub PR reviewer that automatically reviews pull requests and generates fixes. Catches bugs, security issues, and performance problems in seconds.',
  url: 'https://prix.ai',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'GitHub',
  offers: [
    {
      '@type': 'Offer',
      name: 'Starter',
      price: '0',
      priceCurrency: 'USD',
      description: 'Free plan with 5 PR and 5 issue fixes per month for public repositories.',
    },
    {
      '@type': 'Offer',
      name: 'Base',
      price: '7',
      priceCurrency: 'USD',
      description: 'Unlimited PR reviews for professional developers. $9.99/month regular price.',
      alternateName: '$9.99',
    },
    {
      '@type': 'Offer',
      name: 'Pro',
      price: '9.99',
      priceCurrency: 'USD',
      description: 'For teams with unlimited members, admin dashboard, and dedicated support. $19.99/month regular price.',
      alternateName: '$19.99',
    },
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '2847',
    bestRating: '5',
    worstRating: '1',
  },
  featureList: [
    'AI-powered code review',
    'Automated PR review',
    'Security vulnerability scanning',
    'Bug detection',
    'Performance optimization',
    'Fix generation',
    'GitHub integration',
    'GitLab integration',
    'Bitbucket integration',
    'GPT-4 powered reasoning',
    'Zero-configuration setup',
  ],
  provider: {
    '@type': 'Organization',
    name: 'Prix',
    url: 'https://prix.ai',
    foundingDate: '2026',
  },
  softwareVersion: '1.2.0',
  screenshot: 'https://prix.ai/og-image.png',
}